# 阶段1：构建器（命名为 builder）
FROM node:22-alpine AS builder
RUN sed -i 's/dl-cdn.alpinelinux.org/mirrors.aliyun.com/g' /etc/apk/repositories
RUN apk add --no-cache libc6-compat openssl
RUN npm install -g npm@10.9.4
WORKDIR /app
RUN rm -rf .next
RUN rm -rf node_modules
COPY package.json package-lock.json ./
RUN npm ci
COPY . .
RUN npx prisma generate
RUN npm run build

# 阶段2：生产运行（最终镜像）
FROM node:22-alpine
RUN sed -i 's/dl-cdn.alpinelinux.org/mirrors.aliyun.com/g' /etc/apk/repositories
RUN apk add --no-cache libc6-compat openssl
RUN npm install -g npm@10.9.4
WORKDIR /app
COPY --from=builder /app/.next .next
COPY --from=builder /app/node_modules node_modules
COPY --from=builder /app/package.json .
COPY --from=builder /app/.env .env
COPY --from=builder /app/prisma prisma

EXPOSE 10530
CMD ["npm", "start"]